### ISSUE TITLE
How to remove default image filter in PhotosCropViewController

### ISSUE THREAD

**Issue by FedupTech** [muukii/Brightroom#97] opened 2021-04-02 03:39 UTC
@muukii 

after select an image and then present PhotosCropViewController, the image with a default filter. and image resize bar is not showing 

![test](https://user-images.githubusercontent.com/65341800/113377689-9a26fd00-93a7-11eb-8c58-ecefff93de1a.gif)

**Comment by muukii** [comment] 2021-04-02 06:06
@FedupTech 
ooh, it's a bug.
- Please tell me what version you're using.

**Comment by FedupTech** [comment] 2021-04-02 06:07
> @FedupTech
> ooh, it's a bug.
> 
> * Please tell me what version you're using.

alpha 4

**Comment by muukii** [comment] 2021-04-02 06:11
@FedupTech 
hm, okay, it seems pixel-format is wrong to display.
But my environment does not reproduce.

What is device?
Your computer is M1 mac?

**Comment by FedupTech** [comment] 2021-04-02 06:18
> @FedupTech
> hm, okay, it seems pixel-format is wrong to display.
> But my environment does not reproduce.
> 
> What is device?
> Your computer is M1 mac?

iMac running os version 11.2.3

**Comment by FedupTech** [comment] 2021-04-02 06:20
> > @FedupTech
> > hm, okay, it seems pixel-format is wrong to display.
> > But my environment does not reproduce.
> > What is device?
> > Your computer is M1 mac?
> 
> iMac running os version 11.2.3

**Comment by muukii** [comment] 2021-04-02 06:21
What iOS version and iPhone device model in your simulator?

**Comment by FedupTech** [comment] 2021-04-02 06:22
> What iOS version and iPhone device model in your simulator?

The device runned iPhone 12pro(14.4), iPhone 8(12.4), Both device and simulator

**Comment by muukii** [comment] 2021-04-02 06:23
Thanks. I'll check it on my Intel mac
So why did you close this  issue? problem solved?

**Comment by FedupTech** [comment] 2021-04-02 06:26
> Thanks. I'll check it on my Intel mac
> So why did you close this issue? problem solved?
No, it didn't. accidental operation

**Comment by FedupTech** [comment] 2021-04-02 06:26
> Thanks. I'll check it on my Intel mac
> So why did you close this issue? problem solved?

No, it didn't. accidental operation

**Comment by muukii** [comment] 2021-04-02 06:30
@FedupTech Just in case, could you try to reproduce in your own real device?

**Comment by muukii** [comment] 2021-04-02 06:38
I've tried to reproduce it in our Demo application.
In main-branch cbe2d242e1760999a08d4b8a8fbe3e0bcd0dfec2

iPhone 12 Pro, Intel Mac

https://user-images.githubusercontent.com/1888355/113388572-6f4da080-93c9-11eb-887e-fa91db7a67c5.mp4

**Comment by FedupTech** [comment] 2021-04-02 06:40
> @FedupTech Just in case, could you try to reproduce in your own real device?

The original image and image from PhotosCropViewController

![Image from iOS (1)](https://user-images.githubusercontent.com/65341800/113388689-475a3f00-93c1-11eb-94e5-e6034669e16c.jpg)


![Image from iOS](https://user-images.githubusercontent.com/65341800/113388680-43c6b800-93c1-11eb-8436-2a0ed1e0b6f5.jpg)

**Comment by muukii** [comment] 2021-04-02 07:03
hmm,
I don't know why it happens...

If you can, please send me something project which can reproduce it?

**Comment by FedupTech** [comment] 2021-04-02 07:27
> hmm,
> I don't know why it happens...
> 
> If you can, please send me something project which can reproduce it?

I just install brightroom into a new project, it works fine. 

it didn't work out in other project installed brightroom. Weird hmmmmm

**Comment by muukii** [comment] 2021-04-02 07:50
hmm, okay...
Between those project, there are something different configurations?

**Comment by muukii** [comment] 2021-04-02 07:51
It's super interested, I'd like to know what settings cause this issue.

**Comment by FedupTech** [comment] 2021-04-02 07:54
> It's super interested, I'd like to know what settings cause this issue.

There's no difference between both project. 

if I use image from photo library will has issue, if I use image from asset, It worked fine.  I'll try to find out why cause issue

**Comment by muukii** [comment] 2021-04-02 08:02
I see.

What photo library do you use? It looks like a custom image picker.

**Comment by FedupTech** [comment] 2021-04-02 08:04
> I see.
> 
> What photo library do you use? It looks like a custom image picker.

Yes it is 

My code of fetch photos from library 
```
    fileprivate func fetchPhotos() {
        let manager = PHImageManager.default()
        let requestOptions = PHImageRequestOptions()
        requestOptions.isSynchronous = false
        requestOptions.deliveryMode = .highQualityFormat
        let fetchOptions = PHFetchOptions()
        fetchOptions.sortDescriptors = [NSSortDescriptor(key: "creationDate", ascending: false)]
        let results: PHFetchResult = PHAsset.fetchAssets(with: .image, options: fetchOptions)
        if results.count > 0 {
            for i in 0..<results.count {
                let asset = results.object(at: i)
                let size = CGSize(width: self.collectionView.width, height: self.collectionView.height)
                manager.requestImage(for: asset,
                                     targetSize: size,
                                     contentMode: .aspectFill,
                                     options: requestOptions) { (image, _) in
                    if let image = image {
                        self.allImgsArr.append(image)
                        self.collectionView.reloadData()
                    } else {
                        print("error asset to image")
                    }
                }
            }
        } else {
            print("no photos to display")
        }
    }
```

**Comment by muukii** [comment] 2021-04-02 08:07
Thanks,
Can you create a small application that reproduces it?
Let me try to run in my environment.

**Comment by muukii** [comment] 2021-04-02 08:09
oh, wait, I could reproduce it in iOS13 Demo app!
Let me investigate it!

**Comment by FedupTech** [comment] 2021-04-02 08:12
> oh, wait, I could reproduce it in iOS13 Demo app!
> Let me investigate it!

Sure

**Comment by FedupTech** [comment] 2021-04-02 08:20
> oh, wait, I could reproduce it in iOS13 Demo app!
> Let me investigate it!

here's the demo with issue 

[demo.zip](https://github.com/muukii/Brightroom/files/6248507/demo.zip)

**Comment by muukii** [comment] 2021-04-02 08:58
I'm not sure what exactly happened, but I was able to fix it.
https://github.com/muukii/Brightroom/pull/98

**Comment by muukii** [comment] 2021-04-02 09:08
I'm publishing https://github.com/muukii/Brightroom/releases/tag/2.0.0-alpha.5

**Comment by FedupTech** [comment] 2021-04-02 09:09
> I'm publishing https://github.com/muukii/Brightroom/releases/tag/2.0.0-alpha.5

Thx for the help👍

**Comment by muukii** [comment] 2021-04-02 09:10
please wait for this action.
https://github.com/muukii/Brightroom/actions/runs/711225440

**Closed** 2021-04-02 09:56 UTC
Labels: help wanted
